begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Copyright 2010 The Apache Software Foundation  *  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements.  See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership.  The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hbase
operator|.
name|util
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|io
operator|.
name|Writable
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|DataInput
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|DataOutput
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_import
import|import
name|java
operator|.
name|nio
operator|.
name|ByteBuffer
import|;
end_import

begin_comment
comment|/**  * Implements a<i>Bloom filter</i>, as defined by Bloom in 1970.  *<p>  * The Bloom filter is a data structure that was introduced in 1970 and that has been adopted by  * the networking research community in the past decade thanks to the bandwidth efficiencies that it  * offers for the transmission of set membership information between networked hosts.  A sender encodes  * the information into a bit vector, the Bloom filter, that is more compact than a conventional  * representation. Computation and space costs for construction are linear in the number of elements.  * The receiver uses the filter to test whether various elements are members of the set. Though the  * filter will occasionally return a false positive, it will never return a false negative. When creating  * the filter, the sender can choose its desired point in a trade-off between the false positive rate and the size.  *  *<p>  * Originally inspired by  *<a href="http://www.one-lab.org">European Commission One-Lab Project 034819</a>.  *  * @see BloomFilter The general behavior of a filter  *  * @see<a href="http://portal.acm.org/citation.cfm?id=362692&dl=ACM&coll=portal">Space/Time Trade-Offs in Hash Coding with Allowable Errors</a>  */
end_comment

begin_class
specifier|public
class|class
name|ByteBloomFilter
implements|implements
name|BloomFilter
block|{
comment|/** Current file format version */
specifier|public
specifier|static
specifier|final
name|int
name|VERSION
init|=
literal|1
decl_stmt|;
comment|/** Bytes (B) in the array */
specifier|protected
name|long
name|byteSize
decl_stmt|;
comment|/** Number of hash functions */
specifier|protected
specifier|final
name|int
name|hashCount
decl_stmt|;
comment|/** Hash type */
specifier|protected
specifier|final
name|int
name|hashType
decl_stmt|;
comment|/** Hash Function */
specifier|protected
specifier|final
name|Hash
name|hash
decl_stmt|;
comment|/** Keys currently in the bloom */
specifier|protected
name|int
name|keyCount
decl_stmt|;
comment|/** Max Keys expected for the bloom */
specifier|protected
name|int
name|maxKeys
decl_stmt|;
comment|/** Bloom bits */
specifier|protected
name|ByteBuffer
name|bloom
decl_stmt|;
comment|/** Bit-value lookup array to prevent doing the same work over and over */
specifier|private
specifier|static
specifier|final
name|byte
index|[]
name|bitvals
init|=
block|{
operator|(
name|byte
operator|)
literal|0x01
block|,
operator|(
name|byte
operator|)
literal|0x02
block|,
operator|(
name|byte
operator|)
literal|0x04
block|,
operator|(
name|byte
operator|)
literal|0x08
block|,
operator|(
name|byte
operator|)
literal|0x10
block|,
operator|(
name|byte
operator|)
literal|0x20
block|,
operator|(
name|byte
operator|)
literal|0x40
block|,
operator|(
name|byte
operator|)
literal|0x80
block|}
decl_stmt|;
comment|/**    * Loads bloom filter meta data from file input.    * @param meta stored bloom meta data    * @throws IllegalArgumentException meta data is invalid    */
specifier|public
name|ByteBloomFilter
parameter_list|(
name|ByteBuffer
name|meta
parameter_list|)
throws|throws
name|IllegalArgumentException
block|{
name|int
name|version
init|=
name|meta
operator|.
name|getInt
argument_list|()
decl_stmt|;
if|if
condition|(
name|version
operator|!=
name|VERSION
condition|)
throw|throw
operator|new
name|IllegalArgumentException
argument_list|(
literal|"Bad version"
argument_list|)
throw|;
name|this
operator|.
name|byteSize
operator|=
name|meta
operator|.
name|getInt
argument_list|()
expr_stmt|;
name|this
operator|.
name|hashCount
operator|=
name|meta
operator|.
name|getInt
argument_list|()
expr_stmt|;
name|this
operator|.
name|hashType
operator|=
name|meta
operator|.
name|getInt
argument_list|()
expr_stmt|;
name|this
operator|.
name|keyCount
operator|=
name|meta
operator|.
name|getInt
argument_list|()
expr_stmt|;
name|this
operator|.
name|maxKeys
operator|=
name|this
operator|.
name|keyCount
expr_stmt|;
name|this
operator|.
name|hash
operator|=
name|Hash
operator|.
name|getInstance
argument_list|(
name|this
operator|.
name|hashType
argument_list|)
expr_stmt|;
name|sanityCheck
argument_list|()
expr_stmt|;
block|}
comment|/**    * Determines& initializes bloom filter meta data from user config.  Call    * {@link #allocBloom()} to allocate bloom filter data.    * @param maxKeys Maximum expected number of keys that will be stored in this bloom    * @param errorRate Desired false positive error rate.  Lower rate = more storage required    * @param hashType Type of hash function to use    * @param foldFactor When finished adding entries, you may be able to 'fold'    * this bloom to save space.  Tradeoff potentially excess bytes in bloom for    * ability to fold if keyCount is exponentially greater than maxKeys.    * @throws IllegalArgumentException    */
specifier|public
name|ByteBloomFilter
parameter_list|(
name|int
name|maxKeys
parameter_list|,
name|float
name|errorRate
parameter_list|,
name|int
name|hashType
parameter_list|,
name|int
name|foldFactor
parameter_list|)
throws|throws
name|IllegalArgumentException
block|{
comment|/*      * Bloom filters are very sensitive to the number of elements inserted      * into them. For HBase, the number of entries depends on the size of the      * data stored in the column. Currently the default region size is 256MB,      * so entry count ~= 256MB / (average value size for column).  Despite      * this rule of thumb, there is no efficient way to calculate the entry      * count after compactions.  Therefore, it is often easier to use a      * dynamic bloom filter that will add extra space instead of allowing the      * error rate to grow.      *      * ( http://www.eecs.harvard.edu/~michaelm/NEWWORK/postscripts/BloomFilterSurvey.pdf )      *      * m denotes the number of bits in the Bloom filter (bitSize)      * n denotes the number of elements inserted into the Bloom filter (maxKeys)      * k represents the number of hash functions used (nbHash)      * e represents the desired false positive rate for the bloom (err)      *      * If we fix the error rate (e) and know the number of entries, then      * the optimal bloom size m = -(n * ln(err) / (ln(2)^2)      *                         ~= n * ln(err) / ln(0.6185)      *      * The probability of false positives is minimized when k = m/n ln(2).      */
name|long
name|bitSize
init|=
operator|(
name|long
operator|)
name|Math
operator|.
name|ceil
argument_list|(
name|maxKeys
operator|*
operator|(
name|Math
operator|.
name|log
argument_list|(
name|errorRate
argument_list|)
operator|/
name|Math
operator|.
name|log
argument_list|(
literal|0.6185
argument_list|)
operator|)
argument_list|)
decl_stmt|;
name|int
name|functionCount
init|=
operator|(
name|int
operator|)
name|Math
operator|.
name|ceil
argument_list|(
name|Math
operator|.
name|log
argument_list|(
literal|2
argument_list|)
operator|*
operator|(
name|bitSize
operator|/
name|maxKeys
operator|)
argument_list|)
decl_stmt|;
comment|// increase byteSize so folding is possible
name|long
name|byteSize
init|=
operator|(
name|bitSize
operator|+
literal|7
operator|)
operator|/
literal|8
decl_stmt|;
name|int
name|mask
init|=
operator|(
literal|1
operator|<<
name|foldFactor
operator|)
operator|-
literal|1
decl_stmt|;
if|if
condition|(
operator|(
name|mask
operator|&
name|byteSize
operator|)
operator|!=
literal|0
condition|)
block|{
name|byteSize
operator|>>=
name|foldFactor
expr_stmt|;
operator|++
name|byteSize
expr_stmt|;
name|byteSize
operator|<<=
name|foldFactor
expr_stmt|;
block|}
name|this
operator|.
name|byteSize
operator|=
name|byteSize
expr_stmt|;
name|this
operator|.
name|hashCount
operator|=
name|functionCount
expr_stmt|;
name|this
operator|.
name|hashType
operator|=
name|hashType
expr_stmt|;
name|this
operator|.
name|keyCount
operator|=
literal|0
expr_stmt|;
name|this
operator|.
name|maxKeys
operator|=
name|maxKeys
expr_stmt|;
name|this
operator|.
name|hash
operator|=
name|Hash
operator|.
name|getInstance
argument_list|(
name|hashType
argument_list|)
expr_stmt|;
name|sanityCheck
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|allocBloom
parameter_list|()
block|{
if|if
condition|(
name|this
operator|.
name|bloom
operator|!=
literal|null
condition|)
block|{
throw|throw
operator|new
name|IllegalArgumentException
argument_list|(
literal|"can only create bloom once."
argument_list|)
throw|;
block|}
name|this
operator|.
name|bloom
operator|=
name|ByteBuffer
operator|.
name|allocate
argument_list|(
operator|(
name|int
operator|)
name|this
operator|.
name|byteSize
argument_list|)
expr_stmt|;
assert|assert
name|this
operator|.
name|bloom
operator|.
name|hasArray
argument_list|()
assert|;
block|}
name|void
name|sanityCheck
parameter_list|()
throws|throws
name|IllegalArgumentException
block|{
if|if
condition|(
literal|0
operator|>=
name|this
operator|.
name|byteSize
operator|||
name|this
operator|.
name|byteSize
operator|>
name|Integer
operator|.
name|MAX_VALUE
condition|)
block|{
throw|throw
operator|new
name|IllegalArgumentException
argument_list|(
literal|"Invalid byteSize: "
operator|+
name|this
operator|.
name|byteSize
argument_list|)
throw|;
block|}
if|if
condition|(
name|this
operator|.
name|hashCount
operator|<=
literal|0
condition|)
block|{
throw|throw
operator|new
name|IllegalArgumentException
argument_list|(
literal|"Hash function count must be> 0"
argument_list|)
throw|;
block|}
if|if
condition|(
name|this
operator|.
name|hash
operator|==
literal|null
condition|)
block|{
throw|throw
operator|new
name|IllegalArgumentException
argument_list|(
literal|"hashType must be known"
argument_list|)
throw|;
block|}
if|if
condition|(
name|this
operator|.
name|keyCount
operator|<
literal|0
condition|)
block|{
throw|throw
operator|new
name|IllegalArgumentException
argument_list|(
literal|"must have positive keyCount"
argument_list|)
throw|;
block|}
block|}
name|void
name|bloomCheck
parameter_list|(
name|ByteBuffer
name|bloom
parameter_list|)
throws|throws
name|IllegalArgumentException
block|{
if|if
condition|(
name|this
operator|.
name|byteSize
operator|!=
name|bloom
operator|.
name|limit
argument_list|()
condition|)
block|{
throw|throw
operator|new
name|IllegalArgumentException
argument_list|(
literal|"Configured bloom length should match actual length"
argument_list|)
throw|;
block|}
block|}
annotation|@
name|Override
specifier|public
name|void
name|add
parameter_list|(
name|byte
index|[]
name|buf
parameter_list|)
block|{
name|add
argument_list|(
name|buf
argument_list|,
literal|0
argument_list|,
name|buf
operator|.
name|length
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|add
parameter_list|(
name|byte
index|[]
name|buf
parameter_list|,
name|int
name|offset
parameter_list|,
name|int
name|len
parameter_list|)
block|{
comment|/*      * For faster hashing, use combinatorial generation      * http://www.eecs.harvard.edu/~kirsch/pubs/bbbf/esa06.pdf      */
name|int
name|hash1
init|=
name|this
operator|.
name|hash
operator|.
name|hash
argument_list|(
name|buf
argument_list|,
name|offset
argument_list|,
name|len
argument_list|,
literal|0
argument_list|)
decl_stmt|;
name|int
name|hash2
init|=
name|this
operator|.
name|hash
operator|.
name|hash
argument_list|(
name|buf
argument_list|,
name|offset
argument_list|,
name|len
argument_list|,
name|hash1
argument_list|)
decl_stmt|;
for|for
control|(
name|int
name|i
init|=
literal|0
init|;
name|i
operator|<
name|this
operator|.
name|hashCount
condition|;
name|i
operator|++
control|)
block|{
name|long
name|hashLoc
init|=
name|Math
operator|.
name|abs
argument_list|(
operator|(
name|hash1
operator|+
name|i
operator|*
name|hash2
operator|)
operator|%
operator|(
name|this
operator|.
name|byteSize
operator|*
literal|8
operator|)
argument_list|)
decl_stmt|;
name|set
argument_list|(
name|hashLoc
argument_list|)
expr_stmt|;
block|}
operator|++
name|this
operator|.
name|keyCount
expr_stmt|;
block|}
comment|/**    * Should only be used in tests when writing a bloom filter.    */
name|boolean
name|contains
parameter_list|(
name|byte
index|[]
name|buf
parameter_list|)
block|{
return|return
name|contains
argument_list|(
name|buf
argument_list|,
literal|0
argument_list|,
name|buf
operator|.
name|length
argument_list|,
name|this
operator|.
name|bloom
argument_list|)
return|;
block|}
comment|/**    * Should only be used in tests when writing a bloom filter.    */
name|boolean
name|contains
parameter_list|(
name|byte
index|[]
name|buf
parameter_list|,
name|int
name|offset
parameter_list|,
name|int
name|length
parameter_list|)
block|{
return|return
name|contains
argument_list|(
name|buf
argument_list|,
name|offset
argument_list|,
name|length
argument_list|,
name|this
operator|.
name|bloom
argument_list|)
return|;
block|}
annotation|@
name|Override
specifier|public
name|boolean
name|contains
parameter_list|(
name|byte
index|[]
name|buf
parameter_list|,
name|ByteBuffer
name|theBloom
parameter_list|)
block|{
return|return
name|contains
argument_list|(
name|buf
argument_list|,
literal|0
argument_list|,
name|buf
operator|.
name|length
argument_list|,
name|theBloom
argument_list|)
return|;
block|}
annotation|@
name|Override
specifier|public
name|boolean
name|contains
parameter_list|(
name|byte
index|[]
name|buf
parameter_list|,
name|int
name|offset
parameter_list|,
name|int
name|length
parameter_list|,
name|ByteBuffer
name|theBloom
parameter_list|)
block|{
if|if
condition|(
name|theBloom
operator|.
name|limit
argument_list|()
operator|!=
name|this
operator|.
name|byteSize
condition|)
block|{
throw|throw
operator|new
name|IllegalArgumentException
argument_list|(
literal|"Bloom does not match expected size"
argument_list|)
throw|;
block|}
name|int
name|hash1
init|=
name|this
operator|.
name|hash
operator|.
name|hash
argument_list|(
name|buf
argument_list|,
name|offset
argument_list|,
name|length
argument_list|,
literal|0
argument_list|)
decl_stmt|;
name|int
name|hash2
init|=
name|this
operator|.
name|hash
operator|.
name|hash
argument_list|(
name|buf
argument_list|,
name|offset
argument_list|,
name|length
argument_list|,
name|hash1
argument_list|)
decl_stmt|;
for|for
control|(
name|int
name|i
init|=
literal|0
init|;
name|i
operator|<
name|this
operator|.
name|hashCount
condition|;
name|i
operator|++
control|)
block|{
name|long
name|hashLoc
init|=
name|Math
operator|.
name|abs
argument_list|(
operator|(
name|hash1
operator|+
name|i
operator|*
name|hash2
operator|)
operator|%
operator|(
name|this
operator|.
name|byteSize
operator|*
literal|8
operator|)
argument_list|)
decl_stmt|;
if|if
condition|(
operator|!
name|get
argument_list|(
name|hashLoc
argument_list|,
name|theBloom
argument_list|)
condition|)
block|{
return|return
literal|false
return|;
block|}
block|}
return|return
literal|true
return|;
block|}
comment|//---------------------------------------------------------------------------
comment|/** Private helpers */
comment|/**    * Set the bit at the specified index to 1.    *    * @param pos index of bit    */
name|void
name|set
parameter_list|(
name|long
name|pos
parameter_list|)
block|{
name|int
name|bytePos
init|=
call|(
name|int
call|)
argument_list|(
name|pos
operator|/
literal|8
argument_list|)
decl_stmt|;
name|int
name|bitPos
init|=
call|(
name|int
call|)
argument_list|(
name|pos
operator|%
literal|8
argument_list|)
decl_stmt|;
name|byte
name|curByte
init|=
name|bloom
operator|.
name|get
argument_list|(
name|bytePos
argument_list|)
decl_stmt|;
name|curByte
operator||=
name|bitvals
index|[
name|bitPos
index|]
expr_stmt|;
name|bloom
operator|.
name|put
argument_list|(
name|bytePos
argument_list|,
name|curByte
argument_list|)
expr_stmt|;
block|}
comment|/**    * Check if bit at specified index is 1.    *    * @param pos index of bit    * @return true if bit at specified index is 1, false if 0.    */
specifier|static
name|boolean
name|get
parameter_list|(
name|long
name|pos
parameter_list|,
name|ByteBuffer
name|theBloom
parameter_list|)
block|{
name|int
name|bytePos
init|=
call|(
name|int
call|)
argument_list|(
name|pos
operator|/
literal|8
argument_list|)
decl_stmt|;
name|int
name|bitPos
init|=
call|(
name|int
call|)
argument_list|(
name|pos
operator|%
literal|8
argument_list|)
decl_stmt|;
name|byte
name|curByte
init|=
name|theBloom
operator|.
name|get
argument_list|(
name|bytePos
argument_list|)
decl_stmt|;
name|curByte
operator|&=
name|bitvals
index|[
name|bitPos
index|]
expr_stmt|;
return|return
operator|(
name|curByte
operator|!=
literal|0
operator|)
return|;
block|}
annotation|@
name|Override
specifier|public
name|int
name|getKeyCount
parameter_list|()
block|{
return|return
name|this
operator|.
name|keyCount
return|;
block|}
annotation|@
name|Override
specifier|public
name|int
name|getMaxKeys
parameter_list|()
block|{
return|return
name|this
operator|.
name|maxKeys
return|;
block|}
annotation|@
name|Override
specifier|public
name|int
name|getByteSize
parameter_list|()
block|{
return|return
operator|(
name|int
operator|)
name|this
operator|.
name|byteSize
return|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|compactBloom
parameter_list|()
block|{
comment|// see if the actual size is exponentially smaller than expected.
if|if
condition|(
name|this
operator|.
name|keyCount
operator|>
literal|0
operator|&&
name|this
operator|.
name|bloom
operator|.
name|hasArray
argument_list|()
condition|)
block|{
name|int
name|pieces
init|=
literal|1
decl_stmt|;
name|int
name|newByteSize
init|=
operator|(
name|int
operator|)
name|this
operator|.
name|byteSize
decl_stmt|;
name|int
name|newMaxKeys
init|=
name|this
operator|.
name|maxKeys
decl_stmt|;
comment|// while exponentially smaller& folding is lossless
while|while
condition|(
operator|(
name|newByteSize
operator|&
literal|1
operator|)
operator|==
literal|0
operator|&&
name|newMaxKeys
operator|>
operator|(
name|this
operator|.
name|keyCount
operator|<<
literal|1
operator|)
condition|)
block|{
name|pieces
operator|<<=
literal|1
expr_stmt|;
name|newByteSize
operator|>>=
literal|1
expr_stmt|;
name|newMaxKeys
operator|>>=
literal|1
expr_stmt|;
block|}
comment|// if we should fold these into pieces
if|if
condition|(
name|pieces
operator|>
literal|1
condition|)
block|{
name|byte
index|[]
name|array
init|=
name|this
operator|.
name|bloom
operator|.
name|array
argument_list|()
decl_stmt|;
name|int
name|start
init|=
name|this
operator|.
name|bloom
operator|.
name|arrayOffset
argument_list|()
decl_stmt|;
name|int
name|end
init|=
name|start
operator|+
name|newByteSize
decl_stmt|;
name|int
name|off
init|=
name|end
decl_stmt|;
for|for
control|(
name|int
name|p
init|=
literal|1
init|;
name|p
operator|<
name|pieces
condition|;
operator|++
name|p
control|)
block|{
for|for
control|(
name|int
name|pos
init|=
name|start
init|;
name|pos
operator|<
name|end
condition|;
operator|++
name|pos
control|)
block|{
name|array
index|[
name|pos
index|]
operator||=
name|array
index|[
name|off
operator|++
index|]
expr_stmt|;
block|}
block|}
comment|// folding done, only use a subset of this array
name|this
operator|.
name|bloom
operator|.
name|rewind
argument_list|()
expr_stmt|;
name|this
operator|.
name|bloom
operator|.
name|limit
argument_list|(
name|newByteSize
argument_list|)
expr_stmt|;
name|this
operator|.
name|bloom
operator|=
name|this
operator|.
name|bloom
operator|.
name|slice
argument_list|()
expr_stmt|;
name|this
operator|.
name|byteSize
operator|=
name|newByteSize
expr_stmt|;
name|this
operator|.
name|maxKeys
operator|=
name|newMaxKeys
expr_stmt|;
block|}
block|}
block|}
comment|//---------------------------------------------------------------------------
comment|/**    * Writes just the bloom filter to the output array    * @param out OutputStream to place bloom    * @throws IOException Error writing bloom array    */
specifier|public
name|void
name|writeBloom
parameter_list|(
specifier|final
name|DataOutput
name|out
parameter_list|)
throws|throws
name|IOException
block|{
if|if
condition|(
operator|!
name|this
operator|.
name|bloom
operator|.
name|hasArray
argument_list|()
condition|)
block|{
throw|throw
operator|new
name|IOException
argument_list|(
literal|"Only writes ByteBuffer with underlying array."
argument_list|)
throw|;
block|}
name|out
operator|.
name|write
argument_list|(
name|bloom
operator|.
name|array
argument_list|()
argument_list|,
name|bloom
operator|.
name|arrayOffset
argument_list|()
argument_list|,
name|bloom
operator|.
name|limit
argument_list|()
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|Writable
name|getMetaWriter
parameter_list|()
block|{
return|return
operator|new
name|MetaWriter
argument_list|()
return|;
block|}
annotation|@
name|Override
specifier|public
name|Writable
name|getDataWriter
parameter_list|()
block|{
return|return
operator|new
name|DataWriter
argument_list|()
return|;
block|}
specifier|private
class|class
name|MetaWriter
implements|implements
name|Writable
block|{
specifier|protected
name|MetaWriter
parameter_list|()
block|{}
annotation|@
name|Override
specifier|public
name|void
name|readFields
parameter_list|(
name|DataInput
name|arg0
parameter_list|)
throws|throws
name|IOException
block|{
throw|throw
operator|new
name|IOException
argument_list|(
literal|"Cant read with this class."
argument_list|)
throw|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|write
parameter_list|(
name|DataOutput
name|out
parameter_list|)
throws|throws
name|IOException
block|{
name|out
operator|.
name|writeInt
argument_list|(
name|VERSION
argument_list|)
expr_stmt|;
name|out
operator|.
name|writeInt
argument_list|(
operator|(
name|int
operator|)
name|byteSize
argument_list|)
expr_stmt|;
name|out
operator|.
name|writeInt
argument_list|(
name|hashCount
argument_list|)
expr_stmt|;
name|out
operator|.
name|writeInt
argument_list|(
name|hashType
argument_list|)
expr_stmt|;
name|out
operator|.
name|writeInt
argument_list|(
name|keyCount
argument_list|)
expr_stmt|;
block|}
block|}
specifier|private
class|class
name|DataWriter
implements|implements
name|Writable
block|{
specifier|protected
name|DataWriter
parameter_list|()
block|{}
annotation|@
name|Override
specifier|public
name|void
name|readFields
parameter_list|(
name|DataInput
name|arg0
parameter_list|)
throws|throws
name|IOException
block|{
throw|throw
operator|new
name|IOException
argument_list|(
literal|"Cant read with this class."
argument_list|)
throw|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|write
parameter_list|(
name|DataOutput
name|out
parameter_list|)
throws|throws
name|IOException
block|{
name|writeBloom
argument_list|(
name|out
argument_list|)
expr_stmt|;
block|}
block|}
block|}
end_class

end_unit

