begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements.  See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership.  The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hbase
operator|.
name|client
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|concurrent
operator|.
name|TimeUnit
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|yetus
operator|.
name|audience
operator|.
name|InterfaceAudience
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hbase
operator|.
name|thirdparty
operator|.
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|Preconditions
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hbase
operator|.
name|thirdparty
operator|.
name|io
operator|.
name|netty
operator|.
name|util
operator|.
name|HashedWheelTimer
import|;
end_import

begin_comment
comment|/**  * The implementation of {@link AsyncBufferedMutatorBuilder}.  */
end_comment

begin_class
annotation|@
name|InterfaceAudience
operator|.
name|Private
class|class
name|AsyncBufferedMutatorBuilderImpl
implements|implements
name|AsyncBufferedMutatorBuilder
block|{
specifier|private
specifier|final
name|HashedWheelTimer
name|periodicalFlushTimer
decl_stmt|;
specifier|private
specifier|final
name|AsyncTableBuilder
argument_list|<
name|?
argument_list|>
name|tableBuilder
decl_stmt|;
specifier|private
name|long
name|writeBufferSize
decl_stmt|;
specifier|private
name|long
name|periodicFlushTimeoutNs
decl_stmt|;
specifier|public
name|AsyncBufferedMutatorBuilderImpl
parameter_list|(
name|AsyncConnectionConfiguration
name|connConf
parameter_list|,
name|AsyncTableBuilder
argument_list|<
name|?
argument_list|>
name|tableBuilder
parameter_list|,
name|HashedWheelTimer
name|periodicalFlushTimer
parameter_list|)
block|{
name|this
operator|.
name|tableBuilder
operator|=
name|tableBuilder
expr_stmt|;
name|this
operator|.
name|writeBufferSize
operator|=
name|connConf
operator|.
name|getWriteBufferSize
argument_list|()
expr_stmt|;
name|this
operator|.
name|periodicFlushTimeoutNs
operator|=
name|connConf
operator|.
name|getWriteBufferPeriodicFlushTimeoutNs
argument_list|()
expr_stmt|;
name|this
operator|.
name|periodicalFlushTimer
operator|=
name|periodicalFlushTimer
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|AsyncBufferedMutatorBuilder
name|setOperationTimeout
parameter_list|(
name|long
name|timeout
parameter_list|,
name|TimeUnit
name|unit
parameter_list|)
block|{
name|tableBuilder
operator|.
name|setOperationTimeout
argument_list|(
name|timeout
argument_list|,
name|unit
argument_list|)
expr_stmt|;
return|return
name|this
return|;
block|}
annotation|@
name|Override
specifier|public
name|AsyncBufferedMutatorBuilder
name|setRpcTimeout
parameter_list|(
name|long
name|timeout
parameter_list|,
name|TimeUnit
name|unit
parameter_list|)
block|{
name|tableBuilder
operator|.
name|setRpcTimeout
argument_list|(
name|timeout
argument_list|,
name|unit
argument_list|)
expr_stmt|;
return|return
name|this
return|;
block|}
annotation|@
name|Override
specifier|public
name|AsyncBufferedMutatorBuilder
name|setRetryPause
parameter_list|(
name|long
name|pause
parameter_list|,
name|TimeUnit
name|unit
parameter_list|)
block|{
name|tableBuilder
operator|.
name|setRetryPause
argument_list|(
name|pause
argument_list|,
name|unit
argument_list|)
expr_stmt|;
return|return
name|this
return|;
block|}
annotation|@
name|Override
specifier|public
name|AsyncBufferedMutatorBuilder
name|setMaxAttempts
parameter_list|(
name|int
name|maxAttempts
parameter_list|)
block|{
name|tableBuilder
operator|.
name|setMaxAttempts
argument_list|(
name|maxAttempts
argument_list|)
expr_stmt|;
return|return
name|this
return|;
block|}
annotation|@
name|Override
specifier|public
name|AsyncBufferedMutatorBuilder
name|setStartLogErrorsCnt
parameter_list|(
name|int
name|startLogErrorsCnt
parameter_list|)
block|{
name|tableBuilder
operator|.
name|setStartLogErrorsCnt
argument_list|(
name|startLogErrorsCnt
argument_list|)
expr_stmt|;
return|return
name|this
return|;
block|}
annotation|@
name|Override
specifier|public
name|AsyncBufferedMutatorBuilder
name|setWriteBufferSize
parameter_list|(
name|long
name|writeBufferSize
parameter_list|)
block|{
name|Preconditions
operator|.
name|checkArgument
argument_list|(
name|writeBufferSize
operator|>
literal|0
argument_list|,
literal|"writeBufferSize %d must be>= 0"
argument_list|,
name|writeBufferSize
argument_list|)
expr_stmt|;
name|this
operator|.
name|writeBufferSize
operator|=
name|writeBufferSize
expr_stmt|;
return|return
name|this
return|;
block|}
annotation|@
name|Override
specifier|public
name|AsyncBufferedMutatorBuilder
name|setWriteBufferPeriodicFlush
parameter_list|(
name|long
name|timeout
parameter_list|,
name|TimeUnit
name|unit
parameter_list|)
block|{
name|this
operator|.
name|periodicFlushTimeoutNs
operator|=
name|unit
operator|.
name|toNanos
argument_list|(
name|timeout
argument_list|)
expr_stmt|;
return|return
name|this
return|;
block|}
annotation|@
name|Override
specifier|public
name|AsyncBufferedMutator
name|build
parameter_list|()
block|{
return|return
operator|new
name|AsyncBufferedMutatorImpl
argument_list|(
name|periodicalFlushTimer
argument_list|,
name|tableBuilder
operator|.
name|build
argument_list|()
argument_list|,
name|writeBufferSize
argument_list|,
name|periodicFlushTimeoutNs
argument_list|)
return|;
block|}
block|}
end_class

end_unit

