begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements.  See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership.  The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hbase
operator|.
name|regionserver
package|;
end_package

begin_import
import|import
name|java
operator|.
name|nio
operator|.
name|ByteBuffer
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hbase
operator|.
name|classification
operator|.
name|InterfaceAudience
import|;
end_import

begin_comment
comment|/**  * An off heap chunk implementation.  */
end_comment

begin_class
annotation|@
name|InterfaceAudience
operator|.
name|Private
specifier|public
class|class
name|OffheapChunk
extends|extends
name|Chunk
block|{
name|OffheapChunk
parameter_list|(
name|int
name|size
parameter_list|,
name|int
name|id
parameter_list|)
block|{
comment|// better if this is always created fromPool. This should not be called
name|super
argument_list|(
name|size
argument_list|,
name|id
argument_list|)
expr_stmt|;
block|}
name|OffheapChunk
parameter_list|(
name|int
name|size
parameter_list|,
name|int
name|id
parameter_list|,
name|boolean
name|fromPool
parameter_list|)
block|{
name|super
argument_list|(
name|size
argument_list|,
name|id
argument_list|,
name|fromPool
argument_list|)
expr_stmt|;
assert|assert
name|fromPool
operator|==
literal|true
assert|;
block|}
annotation|@
name|Override
name|void
name|allocateDataBuffer
parameter_list|()
block|{
if|if
condition|(
name|data
operator|==
literal|null
condition|)
block|{
name|data
operator|=
name|ByteBuffer
operator|.
name|allocateDirect
argument_list|(
name|this
operator|.
name|size
argument_list|)
expr_stmt|;
name|data
operator|.
name|putInt
argument_list|(
literal|0
argument_list|,
name|this
operator|.
name|getId
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
block|}
end_class

end_unit

