begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|// Generated by the protocol buffer compiler.  DO NOT EDIT!
end_comment

begin_comment
comment|// source: google/protobuf/duration.proto
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hbase
operator|.
name|shaded
operator|.
name|com
operator|.
name|google
operator|.
name|protobuf
package|;
end_package

begin_interface
specifier|public
interface|interface
name|DurationOrBuilder
extends|extends
comment|// @@protoc_insertion_point(interface_extends:google.protobuf.Duration)
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hbase
operator|.
name|shaded
operator|.
name|com
operator|.
name|google
operator|.
name|protobuf
operator|.
name|MessageOrBuilder
block|{
comment|/**    *<pre>    * Signed seconds of the span of time. Must be from -315,576,000,000    * to +315,576,000,000 inclusive.    *</pre>    *    *<code>optional int64 seconds = 1;</code>    */
name|long
name|getSeconds
parameter_list|()
function_decl|;
comment|/**    *<pre>    * Signed fractions of a second at nanosecond resolution of the span    * of time. Durations less than one second are represented with a 0    * `seconds` field and a positive or negative `nanos` field. For durations    * of one second or more, a non-zero value for the `nanos` field must be    * of the same sign as the `seconds` field. Must be from -999,999,999    * to +999,999,999 inclusive.    *</pre>    *    *<code>optional int32 nanos = 2;</code>    */
name|int
name|getNanos
parameter_list|()
function_decl|;
block|}
end_interface

end_unit

