begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|// Generated by the protocol buffer compiler.  DO NOT EDIT!
end_comment

begin_comment
comment|// source: google/protobuf/field_mask.proto
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hbase
operator|.
name|shaded
operator|.
name|com
operator|.
name|google
operator|.
name|protobuf
package|;
end_package

begin_interface
specifier|public
interface|interface
name|FieldMaskOrBuilder
extends|extends
comment|// @@protoc_insertion_point(interface_extends:google.protobuf.FieldMask)
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hbase
operator|.
name|shaded
operator|.
name|com
operator|.
name|google
operator|.
name|protobuf
operator|.
name|MessageOrBuilder
block|{
comment|/**    *<pre>    * The set of field mask paths.    *</pre>    *    *<code>repeated string paths = 1;</code>    */
name|java
operator|.
name|util
operator|.
name|List
argument_list|<
name|java
operator|.
name|lang
operator|.
name|String
argument_list|>
name|getPathsList
parameter_list|()
function_decl|;
comment|/**    *<pre>    * The set of field mask paths.    *</pre>    *    *<code>repeated string paths = 1;</code>    */
name|int
name|getPathsCount
parameter_list|()
function_decl|;
comment|/**    *<pre>    * The set of field mask paths.    *</pre>    *    *<code>repeated string paths = 1;</code>    */
name|java
operator|.
name|lang
operator|.
name|String
name|getPaths
parameter_list|(
name|int
name|index
parameter_list|)
function_decl|;
comment|/**    *<pre>    * The set of field mask paths.    *</pre>    *    *<code>repeated string paths = 1;</code>    */
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hbase
operator|.
name|shaded
operator|.
name|com
operator|.
name|google
operator|.
name|protobuf
operator|.
name|ByteString
name|getPathsBytes
parameter_list|(
name|int
name|index
parameter_list|)
function_decl|;
block|}
end_interface

end_unit

