begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|// Generated by the protocol buffer compiler.  DO NOT EDIT!
end_comment

begin_comment
comment|// source: google/protobuf/wrappers.proto
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hbase
operator|.
name|shaded
operator|.
name|com
operator|.
name|google
operator|.
name|protobuf
package|;
end_package

begin_interface
specifier|public
interface|interface
name|Int64ValueOrBuilder
extends|extends
comment|// @@protoc_insertion_point(interface_extends:google.protobuf.Int64Value)
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hbase
operator|.
name|shaded
operator|.
name|com
operator|.
name|google
operator|.
name|protobuf
operator|.
name|MessageOrBuilder
block|{
comment|/**    *<pre>    * The int64 value.    *</pre>    *    *<code>int64 value = 1;</code>    */
name|long
name|getValue
parameter_list|()
function_decl|;
block|}
end_interface

end_unit

