begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|// Generated by the protocol buffer compiler.  DO NOT EDIT!
end_comment

begin_comment
comment|// source: google/protobuf/api.proto
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hbase
operator|.
name|shaded
operator|.
name|com
operator|.
name|google
operator|.
name|protobuf
package|;
end_package

begin_interface
specifier|public
interface|interface
name|MixinOrBuilder
extends|extends
comment|// @@protoc_insertion_point(interface_extends:google.protobuf.Mixin)
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hbase
operator|.
name|shaded
operator|.
name|com
operator|.
name|google
operator|.
name|protobuf
operator|.
name|MessageOrBuilder
block|{
comment|/**    *<pre>    * The fully qualified name of the API which is included.    *</pre>    *    *<code>optional string name = 1;</code>    */
name|java
operator|.
name|lang
operator|.
name|String
name|getName
parameter_list|()
function_decl|;
comment|/**    *<pre>    * The fully qualified name of the API which is included.    *</pre>    *    *<code>optional string name = 1;</code>    */
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hbase
operator|.
name|shaded
operator|.
name|com
operator|.
name|google
operator|.
name|protobuf
operator|.
name|ByteString
name|getNameBytes
parameter_list|()
function_decl|;
comment|/**    *<pre>    * If non-empty specifies a path under which inherited HTTP paths    * are rooted.    *</pre>    *    *<code>optional string root = 2;</code>    */
name|java
operator|.
name|lang
operator|.
name|String
name|getRoot
parameter_list|()
function_decl|;
comment|/**    *<pre>    * If non-empty specifies a path under which inherited HTTP paths    * are rooted.    *</pre>    *    *<code>optional string root = 2;</code>    */
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hbase
operator|.
name|shaded
operator|.
name|com
operator|.
name|google
operator|.
name|protobuf
operator|.
name|ByteString
name|getRootBytes
parameter_list|()
function_decl|;
block|}
end_interface

end_unit

