begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|// Generated by the protocol buffer compiler.  DO NOT EDIT!
end_comment

begin_comment
comment|// source: google/protobuf/source_context.proto
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hbase
operator|.
name|shaded
operator|.
name|com
operator|.
name|google
operator|.
name|protobuf
package|;
end_package

begin_interface
specifier|public
interface|interface
name|SourceContextOrBuilder
extends|extends
comment|// @@protoc_insertion_point(interface_extends:google.protobuf.SourceContext)
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hbase
operator|.
name|shaded
operator|.
name|com
operator|.
name|google
operator|.
name|protobuf
operator|.
name|MessageOrBuilder
block|{
comment|/**    *<pre>    * The path-qualified name of the .proto file that contained the associated    * protobuf element.  For example: `"google/protobuf/source_context.proto"`.    *</pre>    *    *<code>optional string file_name = 1;</code>    */
name|java
operator|.
name|lang
operator|.
name|String
name|getFileName
parameter_list|()
function_decl|;
comment|/**    *<pre>    * The path-qualified name of the .proto file that contained the associated    * protobuf element.  For example: `"google/protobuf/source_context.proto"`.    *</pre>    *    *<code>optional string file_name = 1;</code>    */
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hbase
operator|.
name|shaded
operator|.
name|com
operator|.
name|google
operator|.
name|protobuf
operator|.
name|ByteString
name|getFileNameBytes
parameter_list|()
function_decl|;
block|}
end_interface

end_unit

