begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|// Generated by the protocol buffer compiler.  DO NOT EDIT!
end_comment

begin_comment
comment|// source: google/protobuf/timestamp.proto
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hbase
operator|.
name|shaded
operator|.
name|com
operator|.
name|google
operator|.
name|protobuf
package|;
end_package

begin_interface
specifier|public
interface|interface
name|TimestampOrBuilder
extends|extends
comment|// @@protoc_insertion_point(interface_extends:google.protobuf.Timestamp)
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hbase
operator|.
name|shaded
operator|.
name|com
operator|.
name|google
operator|.
name|protobuf
operator|.
name|MessageOrBuilder
block|{
comment|/**    *<pre>    * Represents seconds of UTC time since Unix epoch    * 1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to    * 9999-12-31T23:59:59Z inclusive.    *</pre>    *    *<code>int64 seconds = 1;</code>    */
name|long
name|getSeconds
parameter_list|()
function_decl|;
comment|/**    *<pre>    * Non-negative fractions of a second at nanosecond resolution. Negative    * second values with fractions must still have non-negative nanos values    * that count forward in time. Must be from 0 to 999,999,999    * inclusive.    *</pre>    *    *<code>int32 nanos = 2;</code>    */
name|int
name|getNanos
parameter_list|()
function_decl|;
block|}
end_interface

end_unit

