begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements. See the NOTICE file distributed with this  * work for additional information regarding copyright ownership. The ASF  * licenses this file to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance with the License.  * You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT  * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the  * License for the specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hbase
operator|.
name|io
operator|.
name|encoding
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|DataInputStream
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|DataOutput
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|DataOutputStream
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_import
import|import
name|java
operator|.
name|nio
operator|.
name|ByteBuffer
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hbase
operator|.
name|Cell
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hbase
operator|.
name|CellComparator
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hbase
operator|.
name|KeyValue
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hbase
operator|.
name|KeyValueUtil
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hbase
operator|.
name|PrivateCellUtil
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hbase
operator|.
name|nio
operator|.
name|ByteBuff
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hbase
operator|.
name|util
operator|.
name|ByteBufferUtils
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hbase
operator|.
name|util
operator|.
name|Bytes
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|yetus
operator|.
name|audience
operator|.
name|InterfaceAudience
import|;
end_import

begin_comment
comment|/**  * Compress key by storing size of common prefix with previous KeyValue  * and storing raw size of rest.  *  * Format:  * 1-5 bytes: compressed key length minus prefix (7-bit encoding)  * 1-5 bytes: compressed value length (7-bit encoding)  * 1-3 bytes: compressed length of common key prefix  * ... bytes: rest of key (including timestamp)  * ... bytes: value  *  * In a worst case compressed KeyValue will be three bytes longer than original.  *  */
end_comment

begin_class
annotation|@
name|InterfaceAudience
operator|.
name|Private
specifier|public
class|class
name|PrefixKeyDeltaEncoder
extends|extends
name|BufferedDataBlockEncoder
block|{
annotation|@
name|Override
specifier|public
name|int
name|internalEncode
parameter_list|(
name|Cell
name|cell
parameter_list|,
name|HFileBlockDefaultEncodingContext
name|encodingContext
parameter_list|,
name|DataOutputStream
name|out
parameter_list|)
throws|throws
name|IOException
block|{
name|int
name|klength
init|=
name|KeyValueUtil
operator|.
name|keyLength
argument_list|(
name|cell
argument_list|)
decl_stmt|;
name|int
name|vlength
init|=
name|cell
operator|.
name|getValueLength
argument_list|()
decl_stmt|;
name|EncodingState
name|state
init|=
name|encodingContext
operator|.
name|getEncodingState
argument_list|()
decl_stmt|;
if|if
condition|(
name|state
operator|.
name|prevCell
operator|==
literal|null
condition|)
block|{
comment|// copy the key, there is no common prefix with none
name|ByteBufferUtils
operator|.
name|putCompressedInt
argument_list|(
name|out
argument_list|,
name|klength
argument_list|)
expr_stmt|;
name|ByteBufferUtils
operator|.
name|putCompressedInt
argument_list|(
name|out
argument_list|,
name|vlength
argument_list|)
expr_stmt|;
name|ByteBufferUtils
operator|.
name|putCompressedInt
argument_list|(
name|out
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|PrivateCellUtil
operator|.
name|writeFlatKey
argument_list|(
name|cell
argument_list|,
operator|(
name|DataOutput
operator|)
name|out
argument_list|)
expr_stmt|;
block|}
else|else
block|{
comment|// find a common prefix and skip it
name|int
name|common
init|=
name|PrivateCellUtil
operator|.
name|findCommonPrefixInFlatKey
argument_list|(
name|cell
argument_list|,
name|state
operator|.
name|prevCell
argument_list|,
literal|true
argument_list|,
literal|true
argument_list|)
decl_stmt|;
name|ByteBufferUtils
operator|.
name|putCompressedInt
argument_list|(
name|out
argument_list|,
name|klength
operator|-
name|common
argument_list|)
expr_stmt|;
name|ByteBufferUtils
operator|.
name|putCompressedInt
argument_list|(
name|out
argument_list|,
name|vlength
argument_list|)
expr_stmt|;
name|ByteBufferUtils
operator|.
name|putCompressedInt
argument_list|(
name|out
argument_list|,
name|common
argument_list|)
expr_stmt|;
name|writeKeyExcludingCommon
argument_list|(
name|cell
argument_list|,
name|common
argument_list|,
name|out
argument_list|)
expr_stmt|;
block|}
comment|// Write the value part
name|PrivateCellUtil
operator|.
name|writeValue
argument_list|(
name|out
argument_list|,
name|cell
argument_list|,
name|vlength
argument_list|)
expr_stmt|;
name|int
name|size
init|=
name|klength
operator|+
name|vlength
operator|+
name|KeyValue
operator|.
name|KEYVALUE_INFRASTRUCTURE_SIZE
decl_stmt|;
name|size
operator|+=
name|afterEncodingKeyValue
argument_list|(
name|cell
argument_list|,
name|out
argument_list|,
name|encodingContext
argument_list|)
expr_stmt|;
name|state
operator|.
name|prevCell
operator|=
name|cell
expr_stmt|;
return|return
name|size
return|;
block|}
specifier|private
name|void
name|writeKeyExcludingCommon
parameter_list|(
name|Cell
name|cell
parameter_list|,
name|int
name|commonPrefix
parameter_list|,
name|DataOutputStream
name|out
parameter_list|)
throws|throws
name|IOException
block|{
name|short
name|rLen
init|=
name|cell
operator|.
name|getRowLength
argument_list|()
decl_stmt|;
if|if
condition|(
name|commonPrefix
operator|<
name|rLen
operator|+
name|KeyValue
operator|.
name|ROW_LENGTH_SIZE
condition|)
block|{
comment|// Previous and current rows are different. Need to write the differing part followed by
comment|// cf,q,ts and type
name|PrivateCellUtil
operator|.
name|writeRowKeyExcludingCommon
argument_list|(
name|cell
argument_list|,
name|rLen
argument_list|,
name|commonPrefix
argument_list|,
name|out
argument_list|)
expr_stmt|;
name|byte
name|fLen
init|=
name|cell
operator|.
name|getFamilyLength
argument_list|()
decl_stmt|;
name|out
operator|.
name|writeByte
argument_list|(
name|fLen
argument_list|)
expr_stmt|;
name|PrivateCellUtil
operator|.
name|writeFamily
argument_list|(
name|out
argument_list|,
name|cell
argument_list|,
name|fLen
argument_list|)
expr_stmt|;
name|PrivateCellUtil
operator|.
name|writeQualifier
argument_list|(
name|out
argument_list|,
name|cell
argument_list|,
name|cell
operator|.
name|getQualifierLength
argument_list|()
argument_list|)
expr_stmt|;
name|out
operator|.
name|writeLong
argument_list|(
name|cell
operator|.
name|getTimestamp
argument_list|()
argument_list|)
expr_stmt|;
name|out
operator|.
name|writeByte
argument_list|(
name|cell
operator|.
name|getTypeByte
argument_list|()
argument_list|)
expr_stmt|;
block|}
else|else
block|{
comment|// The full row key part is common. CF part will be common for sure as we deal with Cells in
comment|// same family. Just need write the differing part in q, ts and type
name|commonPrefix
operator|=
name|commonPrefix
operator|-
operator|(
name|rLen
operator|+
name|KeyValue
operator|.
name|ROW_LENGTH_SIZE
operator|)
operator|-
operator|(
name|cell
operator|.
name|getFamilyLength
argument_list|()
operator|+
name|KeyValue
operator|.
name|FAMILY_LENGTH_SIZE
operator|)
expr_stmt|;
name|int
name|qLen
init|=
name|cell
operator|.
name|getQualifierLength
argument_list|()
decl_stmt|;
name|int
name|commonQualPrefix
init|=
name|Math
operator|.
name|min
argument_list|(
name|commonPrefix
argument_list|,
name|qLen
argument_list|)
decl_stmt|;
name|int
name|qualPartLenToWrite
init|=
name|qLen
operator|-
name|commonQualPrefix
decl_stmt|;
if|if
condition|(
name|qualPartLenToWrite
operator|>
literal|0
condition|)
block|{
name|PrivateCellUtil
operator|.
name|writeQualifierSkippingBytes
argument_list|(
name|out
argument_list|,
name|cell
argument_list|,
name|qLen
argument_list|,
name|commonQualPrefix
argument_list|)
expr_stmt|;
block|}
name|commonPrefix
operator|-=
name|commonQualPrefix
expr_stmt|;
comment|// Common part in TS also?
if|if
condition|(
name|commonPrefix
operator|>
literal|0
condition|)
block|{
name|int
name|commonTimestampPrefix
init|=
name|Math
operator|.
name|min
argument_list|(
name|commonPrefix
argument_list|,
name|KeyValue
operator|.
name|TIMESTAMP_SIZE
argument_list|)
decl_stmt|;
if|if
condition|(
name|commonTimestampPrefix
operator|<
name|KeyValue
operator|.
name|TIMESTAMP_SIZE
condition|)
block|{
name|byte
index|[]
name|curTsBuf
init|=
name|Bytes
operator|.
name|toBytes
argument_list|(
name|cell
operator|.
name|getTimestamp
argument_list|()
argument_list|)
decl_stmt|;
name|out
operator|.
name|write
argument_list|(
name|curTsBuf
argument_list|,
name|commonTimestampPrefix
argument_list|,
name|KeyValue
operator|.
name|TIMESTAMP_SIZE
operator|-
name|commonTimestampPrefix
argument_list|)
expr_stmt|;
block|}
name|commonPrefix
operator|-=
name|commonTimestampPrefix
expr_stmt|;
if|if
condition|(
name|commonPrefix
operator|==
literal|0
condition|)
block|{
name|out
operator|.
name|writeByte
argument_list|(
name|cell
operator|.
name|getTypeByte
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
else|else
block|{
name|out
operator|.
name|writeLong
argument_list|(
name|cell
operator|.
name|getTimestamp
argument_list|()
argument_list|)
expr_stmt|;
name|out
operator|.
name|writeByte
argument_list|(
name|cell
operator|.
name|getTypeByte
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
block|}
annotation|@
name|Override
specifier|protected
name|ByteBuffer
name|internalDecodeKeyValues
parameter_list|(
name|DataInputStream
name|source
parameter_list|,
name|int
name|allocateHeaderLength
parameter_list|,
name|int
name|skipLastBytes
parameter_list|,
name|HFileBlockDefaultDecodingContext
name|decodingCtx
parameter_list|)
throws|throws
name|IOException
block|{
name|int
name|decompressedSize
init|=
name|source
operator|.
name|readInt
argument_list|()
decl_stmt|;
name|ByteBuffer
name|buffer
init|=
name|ByteBuffer
operator|.
name|allocate
argument_list|(
name|decompressedSize
operator|+
name|allocateHeaderLength
argument_list|)
decl_stmt|;
name|buffer
operator|.
name|position
argument_list|(
name|allocateHeaderLength
argument_list|)
expr_stmt|;
name|int
name|prevKeyOffset
init|=
literal|0
decl_stmt|;
while|while
condition|(
name|source
operator|.
name|available
argument_list|()
operator|>
name|skipLastBytes
condition|)
block|{
name|prevKeyOffset
operator|=
name|decodeKeyValue
argument_list|(
name|source
argument_list|,
name|buffer
argument_list|,
name|prevKeyOffset
argument_list|)
expr_stmt|;
name|afterDecodingKeyValue
argument_list|(
name|source
argument_list|,
name|buffer
argument_list|,
name|decodingCtx
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|source
operator|.
name|available
argument_list|()
operator|!=
name|skipLastBytes
condition|)
block|{
throw|throw
operator|new
name|IllegalStateException
argument_list|(
literal|"Read too many bytes."
argument_list|)
throw|;
block|}
name|buffer
operator|.
name|limit
argument_list|(
name|buffer
operator|.
name|position
argument_list|()
argument_list|)
expr_stmt|;
return|return
name|buffer
return|;
block|}
specifier|private
name|int
name|decodeKeyValue
parameter_list|(
name|DataInputStream
name|source
parameter_list|,
name|ByteBuffer
name|buffer
parameter_list|,
name|int
name|prevKeyOffset
parameter_list|)
throws|throws
name|IOException
throws|,
name|EncoderBufferTooSmallException
block|{
name|int
name|keyLength
init|=
name|ByteBufferUtils
operator|.
name|readCompressedInt
argument_list|(
name|source
argument_list|)
decl_stmt|;
name|int
name|valueLength
init|=
name|ByteBufferUtils
operator|.
name|readCompressedInt
argument_list|(
name|source
argument_list|)
decl_stmt|;
name|int
name|commonLength
init|=
name|ByteBufferUtils
operator|.
name|readCompressedInt
argument_list|(
name|source
argument_list|)
decl_stmt|;
name|int
name|keyOffset
decl_stmt|;
name|keyLength
operator|+=
name|commonLength
expr_stmt|;
name|ensureSpace
argument_list|(
name|buffer
argument_list|,
name|keyLength
operator|+
name|valueLength
operator|+
name|KeyValue
operator|.
name|ROW_OFFSET
argument_list|)
expr_stmt|;
name|buffer
operator|.
name|putInt
argument_list|(
name|keyLength
argument_list|)
expr_stmt|;
name|buffer
operator|.
name|putInt
argument_list|(
name|valueLength
argument_list|)
expr_stmt|;
comment|// copy the prefix
if|if
condition|(
name|commonLength
operator|>
literal|0
condition|)
block|{
name|keyOffset
operator|=
name|buffer
operator|.
name|position
argument_list|()
expr_stmt|;
name|ByteBufferUtils
operator|.
name|copyFromBufferToBuffer
argument_list|(
name|buffer
argument_list|,
name|buffer
argument_list|,
name|prevKeyOffset
argument_list|,
name|commonLength
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|keyOffset
operator|=
name|buffer
operator|.
name|position
argument_list|()
expr_stmt|;
block|}
comment|// copy rest of the key and value
name|int
name|len
init|=
name|keyLength
operator|-
name|commonLength
operator|+
name|valueLength
decl_stmt|;
name|ByteBufferUtils
operator|.
name|copyFromStreamToBuffer
argument_list|(
name|buffer
argument_list|,
name|source
argument_list|,
name|len
argument_list|)
expr_stmt|;
return|return
name|keyOffset
return|;
block|}
annotation|@
name|Override
specifier|public
name|Cell
name|getFirstKeyCellInBlock
parameter_list|(
name|ByteBuff
name|block
parameter_list|)
block|{
name|block
operator|.
name|mark
argument_list|()
expr_stmt|;
name|block
operator|.
name|position
argument_list|(
name|Bytes
operator|.
name|SIZEOF_INT
argument_list|)
expr_stmt|;
name|int
name|keyLength
init|=
name|ByteBuff
operator|.
name|readCompressedInt
argument_list|(
name|block
argument_list|)
decl_stmt|;
comment|// TODO : See if we can avoid these reads as the read values are not getting used
name|ByteBuff
operator|.
name|readCompressedInt
argument_list|(
name|block
argument_list|)
expr_stmt|;
name|int
name|commonLength
init|=
name|ByteBuff
operator|.
name|readCompressedInt
argument_list|(
name|block
argument_list|)
decl_stmt|;
if|if
condition|(
name|commonLength
operator|!=
literal|0
condition|)
block|{
throw|throw
operator|new
name|AssertionError
argument_list|(
literal|"Nonzero common length in the first key in "
operator|+
literal|"block: "
operator|+
name|commonLength
argument_list|)
throw|;
block|}
name|ByteBuffer
name|key
init|=
name|block
operator|.
name|asSubByteBuffer
argument_list|(
name|keyLength
argument_list|)
operator|.
name|duplicate
argument_list|()
decl_stmt|;
name|block
operator|.
name|reset
argument_list|()
expr_stmt|;
return|return
name|createFirstKeyCell
argument_list|(
name|key
argument_list|,
name|keyLength
argument_list|)
return|;
block|}
annotation|@
name|Override
specifier|public
name|String
name|toString
parameter_list|()
block|{
return|return
name|PrefixKeyDeltaEncoder
operator|.
name|class
operator|.
name|getSimpleName
argument_list|()
return|;
block|}
annotation|@
name|Override
specifier|public
name|EncodedSeeker
name|createSeeker
parameter_list|(
name|CellComparator
name|comparator
parameter_list|,
specifier|final
name|HFileBlockDecodingContext
name|decodingCtx
parameter_list|)
block|{
return|return
operator|new
name|BufferedEncodedSeeker
argument_list|<
name|SeekerState
argument_list|>
argument_list|(
name|comparator
argument_list|,
name|decodingCtx
argument_list|)
block|{
annotation|@
name|Override
specifier|protected
name|void
name|decodeNext
parameter_list|()
block|{
name|current
operator|.
name|keyLength
operator|=
name|ByteBuff
operator|.
name|readCompressedInt
argument_list|(
name|currentBuffer
argument_list|)
expr_stmt|;
name|current
operator|.
name|valueLength
operator|=
name|ByteBuff
operator|.
name|readCompressedInt
argument_list|(
name|currentBuffer
argument_list|)
expr_stmt|;
name|current
operator|.
name|lastCommonPrefix
operator|=
name|ByteBuff
operator|.
name|readCompressedInt
argument_list|(
name|currentBuffer
argument_list|)
expr_stmt|;
name|current
operator|.
name|keyLength
operator|+=
name|current
operator|.
name|lastCommonPrefix
expr_stmt|;
name|current
operator|.
name|ensureSpaceForKey
argument_list|()
expr_stmt|;
name|currentBuffer
operator|.
name|get
argument_list|(
name|current
operator|.
name|keyBuffer
argument_list|,
name|current
operator|.
name|lastCommonPrefix
argument_list|,
name|current
operator|.
name|keyLength
operator|-
name|current
operator|.
name|lastCommonPrefix
argument_list|)
expr_stmt|;
name|current
operator|.
name|valueOffset
operator|=
name|currentBuffer
operator|.
name|position
argument_list|()
expr_stmt|;
name|currentBuffer
operator|.
name|skip
argument_list|(
name|current
operator|.
name|valueLength
argument_list|)
expr_stmt|;
if|if
condition|(
name|includesTags
argument_list|()
condition|)
block|{
name|decodeTags
argument_list|()
expr_stmt|;
block|}
if|if
condition|(
name|includesMvcc
argument_list|()
condition|)
block|{
name|current
operator|.
name|memstoreTS
operator|=
name|ByteBufferUtils
operator|.
name|readVLong
argument_list|(
name|currentBuffer
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|current
operator|.
name|memstoreTS
operator|=
literal|0
expr_stmt|;
block|}
name|current
operator|.
name|nextKvOffset
operator|=
name|currentBuffer
operator|.
name|position
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Override
specifier|protected
name|void
name|decodeFirst
parameter_list|()
block|{
name|currentBuffer
operator|.
name|skip
argument_list|(
name|Bytes
operator|.
name|SIZEOF_INT
argument_list|)
expr_stmt|;
name|decodeNext
argument_list|()
expr_stmt|;
block|}
block|}
return|;
block|}
block|}
end_class

end_unit

